file_headers_game = ["game_id",
                     "event",
                     "site",
                     "date_played",
                     "round",
                     "white",
                     "black",
                     "result",
                     "white_elo",
                     "white_rating_diff",
                     "black_elo",
                     "black_rating_diff",
                     "winner",
                     "winner_elo",
                     "loser",
                     "loser_elo",
                     "winner_loser_elo_diff",
                     "eco", "termination",
                     "time_control",
                     "utc_date",
                     "utc_time",
                     "variant",
                     "ply_count",
                     "date_created",
                     "file_name"]

file_headers_moves = ["game_id",
                      "move_no",
                      "notation",
                      "move",
                      "from_square",
                      "to_square",
                      "fen",
                      "is_check",
                      "is_check_mate",
                      "is_fifty_moves",
                      "is_fivefold_repetition",
                      "is_game_over",
                      "is_insufficient_material",
                      "w_count",
                      "b_count",
                      "wp_count",
                      "bp_count",
                      "wq_count",
                      "bq_count",
                      "wb_count",
                      "bb_count",
                      "wn_count",
                      "bn_count",
                      "wr_count",
                      "br_count",
                      "captured_score_for_white",
                      "captured_score_for_black",
                      "fen_row1_w_count",
                      "fen_row2_w_count",
                      "fen_row3_w_count",
                      "fen_row4_w_count",
                      "fen_row5_w_count",
                      "fen_row6_w_count",
                      "fen_row7_w_count",
                      "fen_row8_w_count",
                      "fen_row1_b_count",
                      "fen_row2_b_count",
                      "fen_row3_b_count",
                      "fen_row4_b_count",
                      "fen_row5_b_count", "fen_row6_b_count", "fen_row7_b_count", "fen_row8_b_count",
                      "fen_row1_w_value", "fen_row2_w_value", "fen_row3_w_value", "fen_row4_w_value",
                      "fen_row5_w_value", "fen_row6_w_value", "fen_row7_w_value", "fen_row8_w_value",
                      "fen_row1_b_value", "fen_row2_b_value", "fen_row3_b_value", "fen_row4_b_value",
                      "fen_row5_b_value", "fen_row6_b_value", "fen_row7_b_value", "fen_row8_b_value",
                      "move_sequence"]
